### ISSUE TITLE
Fix integration with SonarLint

### ISSUE THREAD

**Issue by utarwyn** [green-code-initiative/ecoCode-javascript#29]
### Describe the bug

Integration of ecoCode-javascript with SonarLint does not work.
An error is thrown in all files instead of displaying code smell reports

### Versions

- ecoCode-javascript version: **1.4.0 dev**
- SonarQube version: **10.1 or 10.2**

### Screenshots

![image](https://github.com/green-code-initiative/ecoCode-javascript/assets/9255967/0631cd34-791e-4bf2-be91-8343b5a3f4d4)

**Comment by fatenhomrani** [comment]
@ Thomas Trognon

**Comment by Thomxsss** [comment]
Unable to reproduce this issue. After investigation, the SonarQube plugin integration appears to be working correctly.

This issue may no longer be applicable.

**Comment by utarwyn** [comment]
Hello @Thomxsss, awesome news!! 🥳  thank you for the test
So, we can open a PR to enable the SonarLint integration?

**Comment by MP-Aubay** [comment]
Hello @Thomxsss ,

I manage to configure my VSCode with SonarLint (now Sonarqube IDE) and have a similar issue.

Steps to reproduce : 

- Install Sonarqube IDE plugin in VSCode (version 5.2.3)
- Configure "Connected mode" with localhost:9000 and custom token
- Add project binding to "test-project" that should already be analyzed in sonarqube
- Open "Ouput" console with "SonarQube for IDE"
- Open a file of the test project, for example `src/avoid-brightness-override.js`
- See error in Output console

```
2026-05-20 10:46:11.139 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer] TypeError: Key "rules": Key "sonarjs/@creedengo/prefer-lighter-formats-for-image-files": Could not find "@creedengo/prefer-lighter-formats-for-image-files" in plugin "sonarjs".
2026-05-20 10:46:11.141 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at mcc (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:127:18315)
2026-05-20 10:46:11.141 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at yXr.validateRulesConfig (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:127:22249)
2026-05-20 10:46:11.142 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at new yXr (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:127:21401)
2026-05-20 10:46:11.142 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at [finalizeConfig] (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:131:7687)
2026-05-20 10:46:11.143 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at IXr.getConfigWithStatus (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:127:16452)
2026-05-20 10:46:11.143 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at IXr.getConfig (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:127:16550)
2026-05-20 10:46:11.143 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at VXr._verifyWithFlatConfigArray (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:140:1132)
2026-05-20 10:46:11.144 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at VXr.verify (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:136:771)
2026-05-20 10:46:11.145 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at e.lint (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:2447:15236)
2026-05-20 10:46:11.145 [info] [Error - 10:46:11.138] [org.sonar.plugins.javascript.bridge.BridgeServerImpl : nodejs-stream-consumer]     at Tzm (c:\Users\mpicard\.vscode\extensions\sonarsource.sonarlint-vscode-5.2.3-win32-x64\eslint-bridge\package\bin\server.cjs:2447:460587)
...
2026-05-20 10:46:11.149 [info] [Error - 10:46:11.143] [org.sonar.plugins.javascript.analysis.AnalysisProcessor : sonarlint-analysis-scheduler] Failed to analyze file [[uri=file:///c:/DEV/git/green-code-init-2026/creedengo-javascript/test-project/src/avoid-brightness-override.js]]: Key "rules": Key "sonarjs/@creedengo/prefer-lighter-formats-for-image-files": Could not find "@creedengo/prefer-lighter-formats-for-image-files" in plugin "sonarjs".
```

The error seems to indicate that Sonar is looking for the rule in the sonarjs plugin and not in the creedengo plugin.
